// Generated by gencpp from file simple_parking_maneuver/ParkingManeuver.msg
// DO NOT EDIT!


#ifndef SIMPLE_PARKING_MANEUVER_MESSAGE_PARKINGMANEUVER_H
#define SIMPLE_PARKING_MANEUVER_MESSAGE_PARKINGMANEUVER_H

#include <ros/service_traits.h>


#include <simple_parking_maneuver/ParkingManeuverRequest.h>
#include <simple_parking_maneuver/ParkingManeuverResponse.h>


namespace simple_parking_maneuver
{

struct ParkingManeuver
{

typedef ParkingManeuverRequest Request;
typedef ParkingManeuverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParkingManeuver
} // namespace simple_parking_maneuver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_parking_maneuver::ParkingManeuver > {
  static const char* value()
  {
    return "7a31466994d8db49e4cf1556345a8002";
  }

  static const char* value(const ::simple_parking_maneuver::ParkingManeuver&) { return value(); }
};

template<>
struct DataType< ::simple_parking_maneuver::ParkingManeuver > {
  static const char* value()
  {
    return "simple_parking_maneuver/ParkingManeuver";
  }

  static const char* value(const ::simple_parking_maneuver::ParkingManeuver&) { return value(); }
};


// service_traits::MD5Sum< ::simple_parking_maneuver::ParkingManeuverRequest> should match 
// service_traits::MD5Sum< ::simple_parking_maneuver::ParkingManeuver > 
template<>
struct MD5Sum< ::simple_parking_maneuver::ParkingManeuverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_parking_maneuver::ParkingManeuver >::value();
  }
  static const char* value(const ::simple_parking_maneuver::ParkingManeuverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_parking_maneuver::ParkingManeuverRequest> should match 
// service_traits::DataType< ::simple_parking_maneuver::ParkingManeuver > 
template<>
struct DataType< ::simple_parking_maneuver::ParkingManeuverRequest>
{
  static const char* value()
  {
    return DataType< ::simple_parking_maneuver::ParkingManeuver >::value();
  }
  static const char* value(const ::simple_parking_maneuver::ParkingManeuverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_parking_maneuver::ParkingManeuverResponse> should match 
// service_traits::MD5Sum< ::simple_parking_maneuver::ParkingManeuver > 
template<>
struct MD5Sum< ::simple_parking_maneuver::ParkingManeuverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_parking_maneuver::ParkingManeuver >::value();
  }
  static const char* value(const ::simple_parking_maneuver::ParkingManeuverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_parking_maneuver::ParkingManeuverResponse> should match 
// service_traits::DataType< ::simple_parking_maneuver::ParkingManeuver > 
template<>
struct DataType< ::simple_parking_maneuver::ParkingManeuverResponse>
{
  static const char* value()
  {
    return DataType< ::simple_parking_maneuver::ParkingManeuver >::value();
  }
  static const char* value(const ::simple_parking_maneuver::ParkingManeuverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_PARKING_MANEUVER_MESSAGE_PARKINGMANEUVER_H
